import React, { useState } from 'react';
import { X, Copy, Check, Download, Scale } from 'lucide-react';

export default function RegulatoryReportModal({ siteData, onClose }) {
  const [copied, setCopied] = useState(false);

  if (!siteData || !siteData.site) return null;
  const { site, findings = [] } = siteData;

  const generateReportText = () => {
    const lines = [
      'AUTOMATED CONSUMER-UX AUDIT DOSSIER',
      '',
      'INTENDED REVIEWERS: Consumer-protection and compliance teams',
      `INVESTIGATION TARGET: ${site.name} (${site.domain})`,
      `DATE OF AUDIT: ${new Date().toISOString().split('T')[0]}`,
      `MANIPULATION INDEX SCORE: ${site.manipulation_index} / 100 [GRADE: ${site.grade}]`,
      `REGULATORY RISK CLASSIFICATION: ${site.ftc_risk_level}`,
      '',
      '1. EXECUTIVE SUMMARY OF DECEPTIVE PRACTICES',
      '',
      `Automated analysis of ${site.domain} identified ${findings.length} potential deceptive-design findings for human review. These heuristic results are evidence leads, not a legal determination. Each finding should be verified against the complete user journey, underlying business data, current law, and the relevant jurisdiction.`,
      '',
      '2. POTENTIAL FINDINGS AND REVIEW CHECKLIST',
      ''
    ];

    findings.forEach((f, idx) => {
      lines.push(
        `FINDING ${idx + 1}: ${String(f.pattern_name || 'Unclassified pattern').toUpperCase()} [HEURISTIC SEVERITY: ${String(f.severity || 'Unspecified').toUpperCase()}]`,
        `Category: ${f.category || 'N/A'}`,
        `Applicable statutes: ${f.regulatory_statute || 'FTC Act Section 5(a)'} (${f.regulatory_citation || '15 U.S.C. § 45'})`,
        `Forensic plain proof: ${f.plain_explanation || 'N/A'}`,
        `DOM selector proof: ${f.dom_selector || 'N/A'}`,
        `DOM snippet: ${f.dom_snippet || 'N/A'}`,
        `Psychological coercion mechanism: ${f.psychological_mechanism || 'Cognitive Bias Exploitation'}`,
        `Mandated remediation action: ${f.remedy_recommendation || 'Remove deceptive element immediately'}`,
        ''
      );
    });

    lines.push(
      '3. APPLICABLE LEGAL PRECEDENTS AND RULES',
      '',
      '1. FTC Act Section 5 (15 U.S.C. § 45): Prohibition against unfair or deceptive acts or practices affecting commerce.',
      '2. FTC Click-to-Cancel Rule (16 CFR Part 425): Cancellation mechanisms must be as simple and direct as enrollment mechanisms.',
      '3. EU Digital Services Act (Regulation EU 2022/2065 Article 25): Ban on deceptive choice architecture and misleading interface framing.',
      '4. California Honest Pricing Law (SB 478 / Civ. Code § 1770): Prohibition against unadvertised drip fees and hidden handling charges.',
      '',
      'GENERATED BY PATTERN GUARD - AUTOMATED OUTPUT REQUIRING HUMAN AND LEGAL REVIEW'
    );

    return lines.join('\n');
  };

  const reportText = generateReportText();

  const handleCopy = async () => {
    await navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = async () => {
    const { jsPDF } = await import('jspdf');
    const document = new jsPDF({ unit: 'pt', format: 'a4', compress: true });
    const pageWidth = document.internal.pageSize.getWidth();
    const pageHeight = document.internal.pageSize.getHeight();
    const margin = 48;
    const contentWidth = pageWidth - (margin * 2);
    let y = 52;

    document.setProperties({
      title: `Pattern Guard Regulatory Dossier - ${site.domain}`,
      subject: 'Automated consumer UX audit dossier',
      author: 'Pattern Guard',
      creator: 'Pattern Guard'
    });

    const ensureSpace = (height) => {
      if (y + height > pageHeight - 52) {
        document.addPage();
        y = 52;
      }
    };

    const normalizePdfText = (value) => String(value)
      .replace(/[\u2010-\u2015]/g, '-')
      .replace(/\u2026/g, '...')
      .replace(/[^\x09\x0A\x0D\x20-\x7E\u00A0-\u00FF]/g, '');

    const writeText = (text, options = {}) => {
      const {
        fontSize = 10,
        fontStyle = 'normal',
        color = [39, 39, 42],
        indent = 0,
        spaceAfter = 7
      } = options;
      document.setFont('helvetica', fontStyle);
      document.setFontSize(fontSize);
      document.setTextColor(...color);
      const lines = document.splitTextToSize(normalizePdfText(text), contentWidth - indent);
      const lineHeight = fontSize * 1.42;
      lines.forEach((line) => {
        ensureSpace(lineHeight);
        document.text(line, margin + indent, y);
        y += lineHeight;
      });
      y += spaceAfter;
    };

    const writeSectionTitle = (title) => {
      ensureSpace(28);
      document.setDrawColor(59, 130, 246);
      document.setLineWidth(1.5);
      document.line(margin, y - 7, margin + 18, y - 7);
      writeText(title, { fontSize: 13, fontStyle: 'bold', color: [24, 24, 27], indent: 26, spaceAfter: 11 });
    };

    document.setFillColor(10, 10, 12);
    document.rect(0, 0, pageWidth, 108, 'F');
    document.setTextColor(103, 152, 255);
    document.setFont('helvetica', 'bold');
    document.setFontSize(11);
    document.text('PATTERN GUARD', margin, 34);
    document.setTextColor(255, 255, 255);
    document.setFontSize(20);
    document.text('REGULATORY ENFORCEMENT DOSSIER', margin, 64);
    document.setFont('helvetica', 'normal');
    document.setFontSize(9);
    document.setTextColor(180, 180, 186);
    document.text('Automated evidence package for human and legal review', margin, 84);
    y = 136;

    writeText(`Investigation target: ${site.name} (${site.domain})`, { fontStyle: 'bold', fontSize: 11 });
    writeText(`Date of audit: ${new Date().toISOString().split('T')[0]}`);
    writeText(`Manipulation Index: ${site.manipulation_index} / 100     Grade: ${site.grade}     Regulatory risk: ${site.ftc_risk_level}`, { spaceAfter: 16 });

    writeSectionTitle('1. EXECUTIVE SUMMARY OF DECEPTIVE PRACTICES');
    writeText(`Automated analysis of ${site.domain} identified ${findings.length} potential deceptive-design findings for human review. These heuristic results are evidence leads, not a legal determination. Each finding should be verified against the complete user journey, underlying business data, current law, and the relevant jurisdiction.`, { spaceAfter: 16 });

    writeSectionTitle('2. POTENTIAL FINDINGS AND REVIEW CHECKLIST');
    findings.forEach((finding, index) => {
      ensureSpace(48);
      writeText(`FINDING ${index + 1}: ${String(finding.pattern_name || 'Unclassified pattern').toUpperCase()}`, { fontSize: 11, fontStyle: 'bold', color: [30, 64, 175], spaceAfter: 3 });
      writeText(`Heuristic severity: ${String(finding.severity || 'Unspecified').toUpperCase()} | Category: ${finding.category || 'N/A'}`, { fontStyle: 'bold', spaceAfter: 5 });
      writeText(`Applicable statutes: ${finding.regulatory_statute || 'FTC Act Section 5(a)'} (${finding.regulatory_citation || '15 U.S.C. § 45'})`, { indent: 10, spaceAfter: 4 });
      writeText(`Forensic plain proof: ${finding.plain_explanation || 'N/A'}`, { indent: 10, spaceAfter: 4 });
      writeText(`DOM selector proof: ${finding.dom_selector || 'N/A'}`, { indent: 10, spaceAfter: 4 });
      writeText(`DOM snippet: ${finding.dom_snippet || 'N/A'}`, { indent: 10, spaceAfter: 4 });
      writeText(`Psychological coercion mechanism: ${finding.psychological_mechanism || 'Cognitive Bias Exploitation'}`, { indent: 10, spaceAfter: 4 });
      writeText(`Mandated remediation action: ${finding.remedy_recommendation || 'Remove deceptive element immediately'}`, { indent: 10, spaceAfter: 14 });
    });

    writeSectionTitle('3. APPLICABLE LEGAL PRECEDENTS AND RULES');
    writeText('1. FTC Act Section 5 (15 U.S.C. § 45): Prohibition against unfair or deceptive acts or practices affecting commerce.', { indent: 10 });
    writeText('2. FTC Click-to-Cancel Rule (16 CFR Part 425): Cancellation mechanisms must be as simple and direct as enrollment mechanisms.', { indent: 10 });
    writeText('3. EU Digital Services Act (Regulation EU 2022/2065 Article 25): Ban on deceptive choice architecture and misleading interface framing.', { indent: 10 });
    writeText('4. California Honest Pricing Law (SB 478 / Civ. Code § 1770): Prohibition against unadvertised drip fees and hidden handling charges.', { indent: 10, spaceAfter: 18 });
    writeText('AUTOMATED OUTPUT REQUIRING HUMAN AND LEGAL REVIEW', { fontStyle: 'bold', color: [180, 50, 50] });

    const pageCount = document.getNumberOfPages();
    for (let page = 1; page <= pageCount; page += 1) {
      document.setPage(page);
      document.setDrawColor(220, 220, 224);
      document.line(margin, pageHeight - 36, pageWidth - margin, pageHeight - 36);
      document.setFont('helvetica', 'normal');
      document.setFontSize(8);
      document.setTextColor(113, 113, 122);
      document.text('Pattern Guard - Regulatory Enforcement Dossier', margin, pageHeight - 21);
      document.text(`Page ${page} of ${pageCount}`, pageWidth - margin, pageHeight - 21, { align: 'right' });
    }

    const safeDomain = String(site.domain || site.name || 'target').replace(/[^a-z0-9]+/gi, '_');
    document.save(`Pattern_Guard_Dossier_${safeDomain}.pdf`);
  };

  return (
    <div className="fixed inset-0 bg-black/85 z-50 flex items-center justify-center p-3 sm:p-6 backdrop-blur-md">
      <div className="bg-[#121215] border border-white/10 w-full max-w-4xl max-h-[90vh] rounded-2xl flex flex-col shadow-2xl overflow-hidden">
        
        {/* Header */}
        <div className="p-5 border-b border-white/10 bg-[#18181b]/60 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <Scale className="w-4 h-4 text-blue-400" />
            <span className="font-semibold text-sm text-white">
              Official Regulatory Enforcement Dossier
            </span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="bg-white/5 hover:bg-white/10 text-white px-3 py-1.5 rounded-lg text-xs font-mono flex items-center gap-1 border border-white/10 cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied text' : 'Copy text'}</span>
            </button>
            <button
              onClick={handleDownloadPdf}
              className="bg-blue-600 hover:bg-blue-500 text-white px-3.5 py-1.5 rounded-lg text-xs font-mono flex items-center gap-1 cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download PDF</span>
            </button>
            <button onClick={onClose} className="w-8 h-8 rounded-lg hover:bg-white/10 text-zinc-400 hover:text-white flex items-center justify-center cursor-pointer ml-2">
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Plain-text Content Viewer */}
        <div className="p-6 overflow-y-auto bg-[#09090b] text-zinc-300 font-mono text-xs leading-relaxed space-y-4">
          <div className="text-[10px] uppercase tracking-[0.16em] text-zinc-500 border-b border-white/10 pb-3">
            Plain text preview - copied exactly as shown
          </div>
          <pre className="whitespace-pre-wrap font-mono text-xs text-zinc-300 select-all">
            {reportText}
          </pre>
        </div>

      </div>
    </div>
  );
}
