SHOPSNEAK_HTML_STEP1 = """
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ShopSneak — Quantum ANC Pro Headphones</title><link rel="stylesheet" href="/mock/styles.css"></head>
<body><div class="site-shell"><div class="demo-announcement">Free express delivery on orders over $75 · 30-day returns · Member pricing ends tonight</div><nav class="site-nav"><div class="brand"><span class="brand-mark">S</span> ShopSneak <small>Sound, refined</small></div><div class="nav-links"><a>New arrivals</a><a>Headphones</a><a>Speakers</a><a>Support</a></div><div class="nav-actions"><span class="secure-note">◎ Secure checkout</span><span class="avatar">JS</span></div></nav>
<main class="shop-main"><div class="breadcrumbs">Home / Audio / Wireless Headphones / Quantum ANC Pro</div><section class="product-layout"><div class="product-gallery"><div class="product-visual"><span class="visual-label">Studio black · 2025 edition</span><div class="headphone"><span class="headphone-band"></span></div></div><div class="thumb-row"><span class="thumb active"></span><span class="thumb"></span><span class="thumb"></span><span class="thumb"></span></div></div>
<div class="product-copy"><div class="eyebrow">ShopSneak signature audio</div><h1>Quantum ANC Pro<br>Wireless Headphones</h1><div class="rating"><strong>★★★★★</strong> 4.8 · 2,184 verified listeners</div><div class="price-row"><span class="price">$89.00</span><span class="list-price">$129.00</span><span class="sale">Save 31%</span></div><p class="finance">or 4 interest-free payments of $22.25 with ShopPay</p><div class="stock"><span class="stock-dot"></span> In stock — ready to ship today</div><div class="urgency-badge urgency-badge"><strong>HIGH DEMAND</strong> · Only 2 left in stock — 48 people are viewing this now.</div>
<label class="sneak-card selected"><input type="checkbox" checked name="warranty"><span><strong>Add 2-Year Full Accidental Damage Protection Plan</strong><span><b>+$18.99</b> · Pre-selected for your protection</span></span></label><label class="sneak-card"><input type="checkbox" checked name="vip_membership"><span><strong>Enroll in VIP Express Prime Club</strong><span>$9.99/month recurring after your 14-day trial</span></span></label>
<div class="purchase-row"><select class="qty" aria-label="Quantity"><option>Qty 1</option><option>Qty 2</option></select><button id="add-to-cart-button" type="button" onclick="window.location.href='/mock/shopsneak/checkout'" class="primary-cta">Add to cart · $89.00</button></div><p class="delivery">✓ Ships from our US warehouse · Estimated delivery: Tue, Sep 16</p></div></section></main></div></body></html>
"""

SHOPSNEAK_HTML_STEP2 = """
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ShopSneak — Review your order</title><link rel="stylesheet" href="/mock/styles.css"></head>
<body><div class="site-shell"><div class="demo-announcement">Your cart is reserved while you complete checkout</div><nav class="site-nav"><div class="brand"><span class="brand-mark">S</span> ShopSneak <small>Secure checkout</small></div><div class="secure-note">🔒 256-bit encrypted checkout</div></nav><main class="checkout-shell"><div class="checkout-progress"><span><i class="step-dot">1</i> Bag</span><span><i class="step-dot active">2</i> <b>Review</b></span><span><i class="step-dot">3</i> Payment</span></div><div class="checkout-grid"><section class="checkout-card"><h1>Review your order</h1><div class="cart-product"><div class="mini-product"></div><div><strong>Quantum ANC Pro Wireless Headphones</strong><span>Studio black · Quantity 1</span><b>$89.00</b></div></div><div class="deal-countdown-timer">⚡ Cart reserved for <span id="timer">04:59</span> — complete now before items are released</div><div class="line-item muted"><span>Quantum ANC Pro</span><b>$89.00</b></div><div class="line-item"><span>2-Year Accidental Warranty <em>(pre-selected)</em></span><b>$18.99</b></div><div class="line-item warning drip-fee-row"><span>Platform Regulatory &amp; Convenience Fee</span><b>$7.50</b></div><div class="line-item warning drip-fee-row"><span>Mandatory Studio Handling Surcharge</span><b>$4.85</b></div><div class="total-row checkout-final-total"><span>Total due now</span><b>$120.34</b></div><div class="hidden-disclosure"><p>By placing this order, you agree to recurring annual membership auto-renews at $119/year unless cancelled by certified registered mail 30 days prior. Non-refundable.</p></div></section><aside class="payment-card"><h2>One step from better sound.</h2><p>Review the total above, then confirm your secure payment to complete the order.</p><button class="pay-button primary-upsell">AUTHORIZE PAYMENT · $120.34</button><a href="/mock/shopsneak" class="subtle-link subtle-link">No thanks, I don't want to save money and prefer paying full price</a><p class="subtle-link">Secure transaction · Easy returns</p></aside></div></main></div><script>let sec=299;setInterval(()=>{if(sec>0)sec--;const m=String(Math.floor(sec/60)).padStart(2,'0');const s=String(sec%60).padStart(2,'0');document.getElementById('timer').innerText=m+':'+s;},1000);</script></body></html>
"""

GYMTRAP_HTML_SIGNUP = """
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GymTrap Elite — Train your best</title><link rel="stylesheet" href="/mock/styles.css"></head>
<body class="gym-shell"><nav class="gym-nav"><div class="gym-brand">GYM<em>TRAP</em></div><span>Already a member? Sign in</span></nav><main class="gym-hero"><div><span class="gym-pill">Built for your momentum</span><h1>Train with a plan<br>that adapts to you.</h1><p>Structured workouts, intelligent meal tracking, and a motivating community that makes every week count.</p></div><section class="trial-panel"><h2>Start your 7-day reset</h2><p>Personalized training starts the moment you join.</p><div class="trial-list">✓ 500+ guided workouts<br>✓ Personalised weekly plan<br>✓ Smart meal and streak tracking</div><a href="/mock/gymtrap/dashboard" class="trial-cta">START 1-CLICK FREE TRIAL →</a><div class="tiny-note">No commitment today · Cancel anytime from your account</div></section></main></body></html>
"""

GYMTRAP_HTML_DASHBOARD = """
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GymTrap Elite — Your dashboard</title><link rel="stylesheet" href="/mock/styles.css"></head>
<body class="gym-dashboard"><div class="dash-layout"><aside class="dash-side"><div class="gym-brand">GYM<em>TRAP</em></div><div class="side-label">Workspace</div><div class="side-item active">◉ Today</div><div class="side-item">◫ My program</div><div class="side-item">◌ Nutrition</div><div class="side-item">◔ Progress</div><div class="side-label">Account</div><div class="side-item">Settings</div></aside><main class="dash-content"><header class="dash-top"><div><p class="eyebrow">Thursday, September 11</p><h1>Good evening, Jamie.</h1></div><span class="plan-chip">● Active plan · $49/mo</span></header><section class="metric-grid"><div class="metric"><span>Current streak</span><b>12 days 🔥</b></div><div class="metric"><span>Weekly sessions</span><b>3 of 4</b></div><div class="metric"><span>Recovery score</span><b>84 / 100</b></div></section><section class="workout-card"><h2>Today’s focus — Upper body strength</h2><div class="workout-row"><span>42 min · Intermediate · 6 exercises</span><b>Start workout →</b></div></section><a href="/mock/gymtrap/cancel-1" class="cancel-link">Manage / Cancel Membership</a></main></div></body></html>
"""

def cancellation_page(step, title, body, primary_text, primary_href, decline_text, decline_href, extra=""):
    return f"""<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>GymTrap — Cancel Step {step} of 4</title><link rel=\"stylesheet\" href=\"/mock/styles.css\"></head><body class=\"cancel-page\"><section class=\"cancel-frame cancel-flow-step\"><header class=\"cancel-header\"><div class=\"gym-brand\">GYM<em>TRAP</em></div><div class=\"cancel-progress\">Cancellation · <b>Step {step} of 4</b></div></header><main class=\"cancel-body\"><div class=\"flow-step\">Account change request</div><h1>{title}</h1><p>{body}</p>{extra}<div class=\"action-stack\"><a href=\"{primary_href}\" class=\"keep-button {'green' if step == 2 else ''} primary-upsell\">{primary_text}</a><a href=\"{decline_href}\" class=\"decline-offer subtle-link\">{decline_text}</a></div></main></section></body></html>"""

GYMTRAP_HTML_CANCEL_1 = cancellation_page(1, "Are you sure you want to surrender your progress?", "If you cancel today, all your personalized workout plans, streak multipliers, and meal records will be permanently deleted forever.", "Keep My Membership & Stay Healthy", "/mock/gymtrap/dashboard", "No thanks, I don't care about my health and want to give up my discount", "/mock/gymtrap/cancel-2", "<div class='risk-card'>⚠️ 87% of members who pause or cancel report regressing to old habits within 14 days.</div>")
GYMTRAP_HTML_CANCEL_2 = cancellation_page(2, "An exclusive retention grant was unlocked", "Because we value you, we have credited an immediate 70% discount ($14.99/mo instead of $49/mo) to your profile.", "CLAIM 70% DISCOUNT & STAY", "/mock/gymtrap/dashboard", "No, I prefer to pay full price elsewhere", "/mock/gymtrap/cancel-3", "<div class='retention-card'><b>70% OFF FOREVER</b><span>Apply this grant with one click.</span></div>")
GYMTRAP_HTML_CANCEL_3 = cancellation_page(3, "Mandatory exit interview", "Please complete this mandatory 8-question evaluation before cancellation routing.", "Return to Dashboard", "/mock/gymtrap/dashboard", "Proceed to Final Confirmation", "/mock/gymtrap/cancel-4", "<div class='form-card'><label>Why are you leaving us today?<select><option>Too expensive</option><option>Achieved fitness goal</option><option>Switching to local gym</option></select></label></div>")
GYMTRAP_HTML_CANCEL_4 = cancellation_page(4, "Phone verification required", "To prevent unauthorized account closure, online cancellation is disabled for your security. Please call our membership verification specialists:", "Keep Active & Return to Home", "/mock/gymtrap/dashboard", "Return to your account", "/mock/gymtrap/dashboard", "<div class='support-card call-support-wall'><b>☎ 1-800-555-0199</b><span>Available Mon–Fri 9:00 AM – 4:30 PM EST · Average wait: 35 mins</span></div>")
